import { Language } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: "Esat Solitaire",
    newGame: "New Game",
    resumeGame: "Resume Game",
    statistics: "Statistics",
    totalGames: "Games Played",
    wins: "Wins",
    losses: "Losses",
    menu: "Menu",
    score: "Score",
    moves: "Moves",
    time: "Time",
    customize: "Customize Cards",
    aiPromptPlaceholder: "Describe a card back style (e.g., Galaxy, Ancient Egypt)...",
    generate: "Generate with AI",
    generating: "Dreaming...",
    musicOn: "Music On",
    musicOff: "Music Off",
    undo: "Undo",
    autoWin: "Auto Win",
    foundationPlaceholder: "A",
    diffEasy: "Easy (1 Suit)",
    diffMedium: "Medium (2 Suits)",
    diffHard: "Hard (4 Suits)",
    selectDiff: "Select Difficulty",
  },
  ar: {
    title: "سوليتير أسعد",
    newGame: "لعبة جديدة",
    resumeGame: "إكمال اللعبة",
    statistics: "سجل اللعب",
    totalGames: "عدد مرات اللعب",
    wins: "عدد مرات الفوز",
    losses: "عدد مرات الخسارة",
    menu: "القائمة",
    score: "النقاط",
    moves: "الحركات",
    time: "الوقت",
    customize: "تخصيص البطاقات",
    aiPromptPlaceholder: "صف خلفية البطاقة (مثال: فضاء، مصر القديمة)...",
    generate: "توليد بالذكاء الاصطناعي",
    generating: "جاري التوليد...",
    musicOn: "تشغيل الموسيقى",
    musicOff: "إيقاف الموسيقى",
    undo: "تراجع",
    autoWin: "فوز تلقائي",
    foundationPlaceholder: "A",
    diffEasy: "سهل (نوع واحد)",
    diffMedium: "متوسط (نوعين)",
    diffHard: "صعب (4 أنواع)",
    selectDiff: "اختر الصعوبة",
  },
  tr: {
    title: "Esat Solitaire",
    newGame: "Yeni Oyun",
    resumeGame: "Oyuna Devam Et",
    statistics: "İstatistikler",
    totalGames: "Oynanan Oyun",
    wins: "Kazanılan",
    losses: "Kaybedilen",
    menu: "Menü",
    score: "Puan",
    moves: "Hamleler",
    time: "Zaman",
    customize: "Kartları Özelleştir",
    aiPromptPlaceholder: "Bir kart arkası stili tanımlayın (örn. Galaksi)...",
    generate: "AI ile Oluştur",
    generating: "Oluşturuluyor...",
    musicOn: "Müzik Açık",
    musicOff: "Müzik Kapalı",
    undo: "Geri Al",
    autoWin: "Otomatik Bitir",
    foundationPlaceholder: "A",
    diffEasy: "Kolay (1 Tip)",
    diffMedium: "Orta (2 Tip)",
    diffHard: "Zor (4 Tip)",
    selectDiff: "Zorluk Seç",
  },
  de: {
    title: "Esat Solitaire",
    newGame: "Neues Spiel",
    resumeGame: "Spiel fortsetzen",
    statistics: "Statistiken",
    totalGames: "Gespielt",
    wins: "Gewonnen",
    losses: "Verloren",
    menu: "Menü",
    score: "Punkte",
    moves: "Züge",
    time: "Zeit",
    customize: "Karten anpassen",
    aiPromptPlaceholder: "Beschreibe einen Kartenrücken (z.B. Galaxis)...",
    generate: "Mit KI generieren",
    generating: "Generieren...",
    musicOn: "Musik An",
    musicOff: "Musik Aus",
    undo: "Rückgängig",
    autoWin: "Auto-Gewinn",
    foundationPlaceholder: "A",
    diffEasy: "Leicht (1 Farbe)",
    diffMedium: "Mittel (2 Farben)",
    diffHard: "Schwer (4 Farben)",
    selectDiff: "Schwierigkeit",
  }
};

export const RELAXING_MUSIC_URL = "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=lofi-study-112778.mp3";